### PR TITLE
Add User Profile Picture

### LINKED ISSUE #117: Add Profile Picture to User Profile
Enhance user experience by enabling users to upload and display a profile picture, adding a personal touch to their profiles.

### PR DESCRIPTION
**Pull request by SaarOrus**
This PR adds the ability for users to upload and display profile pictures. The following changes have been made:
- New Profile Picture Feature: Users can now upload and set a profile picture. The profile picture will be displayed alongside their username and other relevant information.
- Dependency Update: The "Pillow" library has been added as a project dependency to handle image processing and manipulation.

Users without a profile picture will get the default picture:
deafault profile pic

Example for a user that uploaded a profile picture:
with profilepic

Resolves #117

### CODE REVIEW

**Review by Sendy459 — APPROVED** [review]

**Review by rotem2022 — APPROVED** [review]
LGTM

**Review by talko611 — APPROVED** [review]

**Comment by ygalblum** [comment]
@kobihk for me LGTM. But, I wanted you to take a look at the manual change to the migration file dependency.

The reason @SaarOrus had to do this was that you cannot create static entities before the migration because the code uses the new class that expect the DB schema to be the latest.

Is this manual change OK?

**Comment by rotem2022** [comment]
Maybe it will be better to add the pip install Pillow into the setup file?

**Review by ygalblum — CHANGES_REQUESTED** [review]
@rotem2022 is right in the need to add it. I think it should go into the Pipenv file (in the `packages` section)

**Comment by kobihk** [comment]
@SaarOrus when I try to run it locally I failed with the following error:

    default: + pipenv run python manage.py migrate
    default: SystemCheckError: System check identified some issues:
    default: 
    default: ERRORS:
    default: users.Profile.image: (fields.E210) Cannot use ImageField because Pillow is not installed.
    default: 	HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".

please fix it

**Review by Sendy459 — DISMISSED** [review]

**Review by kobihk — APPROVED** [review]

**Review by talko611 — APPROVED** [review]

**Review by rotem2022 — APPROVED** [review]

**Pull request merged**
